on:
  push:
    branches:
      - main
      
name: main

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple


      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6'
          
      - name: test
        run: |
          cd src
          dotnet test

      - name: publish on nuget.org
        id: publish_nuget
        if: ${{ steps.release.outputs.release_created }}
        run: |
          dotnet pack -c Release -p:version=$version
          dotnet nuget push bin\Release\SharpyEasy.$version.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
        env:
          version: ${{ steps.release.outputs.major }}.${{steps.release.outputs.minor}}.${{steps.release.outputs.patch}}
